# Generated by Django 3.2.9 on 2021-11-25 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(choices=[('B', 'Bro!'), ('S', 'Sis!')], default=None, max_length=4)),
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
