# Generated by Django 3.2.9 on 2021-11-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brosis', '0002_auto_20211119_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(choices=[('B', 'Bro!'), ('S', 'Sis!')], default=None, max_length=4),
        ),
    ]
